[package]
name = "dark-pool-zama"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { version = "~1.2.0", features = ["boolean", "shortint", "integer"] }

[lib]
name = "dark_pool"
path = "src/lib.rs"
